#!/bin/bash
set -exo pipefail

# Refernce: https://dustymabe.com/2019/01/04/easy-pxe-boot-testing-with-only-http-using-ipxe-and-libvirt/

export ISO_NAME=fedora-coreos-30.20190801.0-installer.iso
export RAW_NAME=fedora-coreos-30.20190801.0-metal.raw.xz

export ISO_LINK=https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20190801.0/x86_64/$ISO_NAME
export RAW_LINK=https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20190801.0/x86_64/$RAW_NAME

echo "setup syslinux-nonlinux"
sudo dnf install -y syslinux-nonlinux
cp /usr/share/syslinux/{pxelinux.0,ldlinux.c32} ./

echo "downloading metal image"
wget -O $RAW_NAME $RAW_LINK

echo "downloading iso image"
mkdir .download && cd .download
wget -O $ISO_NAME $ISO_LINK
export ISO_PATH=$(readlink -f $ISO_NAME)
cd ..

echo "mounting iso image"
mkdir $ISO_NAME && sudo mount -o loop $ISO_PATH ./$ISO_NAME
ls $ISO_NAME/images

echo "writing pxelinux.cfg/default"
mkdir pxelinux.cfg
cat <<EOF > pxelinux.cfg/default
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL $ISO_NAME/images/vmlinuz
    APPEND ip=dhcp rd.neednet=1 initrd=$ISO_NAME/images/initramfs.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://192.168.124.1:8000/$RAW_NAME coreos.inst.ignition_url=http://192.168.124.1:8000/config.ign
IPAPPEND 2
EOF

echo "writing kickstart.cfg"
cat <<EOF > kickstart.cfg
url --url http://192.168.124.1:8000/$ISO_NAME/
reboot
rootpw --plaintext foobar
services --enabled="sshd,chronyd"
zerombr
clearpart --all
autopart --type lvm
%packages
@core
%end
EOF

echo "wrting base ignition config"
cat <<EOF > config.ign
{
    "ignition": {
        "version": "3.0.0"
    },
    "storage": {
        "files": [
            {
                "path": "/etc/sysctl.d/10-coreos-assembler.conf",
                "contents": { "source": "data:text/plain;base64,${coreos_assembler_sysctl}" },
                "mode": 420
            },
            {
                "path": "/etc/motd",
                "append": [
                    { "source": "data:text/plain;base64,${coreos_assembler_motd}" }
                ],
                "mode": 420
            }
        ]
    },
    "systemd": {
        "units": [
            {
                "name": "serial-getty@${VM_TERMINAL}.service",
                "dropins": [
                    {
                        "name": "autologin-core.conf",
                        "contents": "[Service]\\nTTYVTDisallocate=no\\nExecStart=\\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I \$TERM\\n"
                    }
                ]
            }
            ${ign_var_srv_mount}
        ]
    }
}
EOF

echo "Finish setup"
echo "Add <bootp file='http://192.168.124.1:8000/pxelinux.0'/> under <dhcp></dhcp>"

# sudo python3 -m http.server
# sudo virsh net-destroy default
# sudo virsh net-edit default
# sudo virsh net-start default
# sudo virt-install --pxe --network network=default --name pxe --memory 2048 --disk size=10 --nographics --boot menu=on,useserial=on

# sudo virsh destroy pxe
# sudo virsh undefine pxe --remove-all-storage --wipe-storage
# sudo umount $ISO_NAME && rm -rf $ISO_NAME
